version: "3.8"

services:
  service1:
    build: ./service1
    container_name: service1
    volumes:
      - ./logs:/logs
    depends_on:
      - service2

  service2:
    build: ./service2
    container_name: service2
    volumes:
      - ./logs:/logs
    ports:
      - "8000:8000"

